const OK_STATUS = 0;
const INVALID_EMPLOYEE_ID = 1;
const INVALID_SUPERVISOR_ID = 2;
const FIRED_SUPERVISOR = 3;
const DIRECTOR_EXISTS = 4;
const NOT_FIRED_EMPLOYEE = 5;
const ALREADY_FIRED = 6;
const SUPERVISOR_NOT_SUBORDINATE = 7;